name: deploy-book

on:
  workflow_dispatch:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Jupyter Book
        run: |
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build ./book

      - name: Deploy to GitHub Pages  # push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html

          